import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
export default function Home() {
const [nowPlaying, setNowPlaying] = useState({title:"Raining sound", link:"https://www.soundjay.com/nature/rain-03.mp3"});
const [playlist, setPlaylist] = useState([
    { title: "Raining sound", link: "https://www.soundjay.com/nature/rain-03.mp3" },
    { title: "báo hỷ", link: "https://zingmp3.vn/bai-hat/Bao-Hy-JGKiD/ZW7O9E7U.html" },
]);
return (
    <div className={styles.container}>
        <Head>
            <title>Learning Animations</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <div className={styles.wrapper}>
                <div className={styles.marqueeContainer}>
                    <div className={styles.portal} />
                    <div className={styles.blur} />
                    <span className={styles.marquee}>{nowPlaying.title}</span>
                    <div className={styles.portal} />
                </div>
                <div className={styles.controllers}></div>
                <div className={styles.playlist}>
                    <h1>PLAYLIST</h1>
                    <div className={styles.blur}></div>
                    <div className={styles.playlistitems}>
                        <ol>
                            {playlist.map((song, index) => (
                                <li
                                    className={song.title === nowPlaying.title ? styles.nowPlaying : ""}
                                    key={setNowPlaying.title}
                                >
                                    {song.title}
                                </li>
                            ))}
                        </ol>
                    </div>
                </div>
            </div>
        </main>

        <footer className={styles.footer}>
            <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
            ></a>
        </footer>
    </div>
);
}
