import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import ReactPlayer from "react-player";
export default function Home() {
    const [playlist, setPlaylist] = useState([
        {
            name: "My, nah, your playlist",
            src: "https://www.youtube.com/playlist?list=PLktFEPieLGU-UKQYl2huD770l-yzftC0n",
        },
        { name: "7UPPERCUTS x Đá Số Tới / Tuyển tập Pop Punks", src: "https://youtu.be/22nk6yEPlfA" },
        { name: "Lukas Graham - Happy Home", src: "https://youtu.be/QX6UhufF0cs" },
    ]);
const [nowPlaying, setNowPlaying] = useState(playlist[0]);
const onNowPlayingEnded = () =>{
    const nowPlayingIndex = playlist.findIndex(p => p.name === nowPlaying.name)
    setNowPlaying(playlist[nowPlayingIndex+1]);
}
return (
    <div className={styles.container}>
        <Head>
            <title>Listening to some songs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/song.ico" />
        </Head>
        <main className={styles.main}>
            <div className={styles.wrapper}>
                <div className={styles.marqueeContainer}>
                    <div className={styles.portal} />
                    <div className={styles.blur} />
                    <span className={styles.marquee}>{nowPlaying.name}</span>
                    <div className={styles.portal} />
                </div>
                <div className={styles.controllers}>
                    <ReactPlayer
                        controls={true}
                        url={nowPlaying.src}
                        width="100%"
                        height="100%"
                        onEnded={onNowPlayingEnded}
                    />
                </div>
                <div className={styles.playlist}>
                    <h1>PLAYLIST</h1>
                    <div className={styles.blur}></div>
                    <div className={styles.playlistitems}>
                        <ol>
                            {playlist.map((song, index) => (
                                <li className={song.name === nowPlaying.name ? styles.nowPlaying : ""} key={song.name}>
                                    {song.name}
                                </li>
                            ))}
                        </ol>
                    </div>
                </div>
            </div>
        </main>

        <footer className={styles.footer}>
            <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
            ></a>
        </footer>
    </div>
);
}
